# Generated by Django 4.0.6 on 2022-08-06 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_part', models.CharField(max_length=50)),
                ('small_introduction', models.TextField()),
                ('big_introduction', models.TextField()),
                ('cause', models.TextField()),
                ('solution', models.TextField()),
                ('image', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
