# Generated by Django 4.0.6 on 2022-08-13 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_symptom'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reservation_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
